version: '3.8'
services:
  app:
    image: club-website-2.0
    build:
      context: ./
      # Set target: production to run in production mode
      target: dev
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"